[package]
name = "parse64"
version = "0.1.0"
authors = ["bigbass1997 <bigbass1997.website@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.20"
strum_macros ="0.20"
colored = "2"